server:
  port: 8000
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=UTF-8
    data-username: root
    password: MySQLDB31
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect